# Generated by Django 4.2.1 on 2023-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.FileField(upload_to='media'),
        ),
    ]
